import './globals.css'
import { yekan } from '@/utils/fonts'
import Layout from '@/template/Layout'
import NextAuthProvider from '@/providers/NextAuthProvider'
import 'bootstrap/dist/css/bootstrap.min.css';
import 'swiper/css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir='rtl'>
      <body className={yekan.className}>
        <NextAuthProvider>
          <Layout>{children}</Layout>
        </NextAuthProvider>
      </body>
    </html>
  )
}
